In [1]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
import pandas as pd
import numpy as np

In [3]:
mtcars = pd.read_csv('mt_cars.csv')
mtcars.head()

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [4]:
X = mtcars[['mpg','hp']].values
y = mtcars['cyl'].values

In [5]:
knn = KNeighborsClassifier(n_neighbors=3)
model = knn.fit(X, y)

In [6]:
model

KNeighborsClassifier(n_neighbors=3)

In [7]:
y_pred = model.predict(X)
print(y_pred)

[6 6 4 6 8 6 8 4 4 6 6 8 8 8 8 8 8 4 4 4 4 8 8 8 8 4 4 4 8 8 8 6]

In [9]:
accuracy = accuracy_score(y, y_pred)
precision = precision_score(y, y_pred, average='weighted')
recall = recall_score(y, y_pred, average='weighted')
f1 = f1_score(y, y_pred, average='weighted')
cm = confusion_matrix(y, y_pred)
print(f'Accuracy: {accuracy:.2f}, Precision: {precision:.2f}, Recall: {recall:.2f}, F1 Score: {f1:.2f}')
print('Confusion Matrix:')
print(cm)

Accuracy: 0.94, Precision: 0.94, Recall: 0.94, F1 Score: 0.94
Confusion Matrix:
[[10  1  0]
 [ 0  6  1]
 [ 0  0 14]]

In [11]:
new_data = np.array([[19.3, 105]])

new_prediction = model.predict(new_data)
print(new_prediction)

distances, indices = knn.kneighbors(new_data)
print(f'Distances: {distances}, Indices: {indices}')

[6]
Distances: [[1.2        4.5177428  5.28109837]], Indices: [[ 5 31  1]]

In [13]:
mtcars.loc[[1,5,31], ['mpg','hp','cyl']]

     mpg   hp  cyl
1   21.0  110    6
5   18.1  105    6
31  21.4  109    4