In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [2]:
with open('Transacoes.txt', "r") as f:
    transacoes = [linha.strip().split(',') for linha in f.readlines()]

transacoes

[['PAINEL', 'BANCOS', 'BOLSA DA PORTA', 'ESTRIBO'],
 ['BANCOS', 'ALARME', 'BOLSA DA PORTA'],
 ['PAINEL', 'ALARME', 'ESTRIBO'],
 ['BANCOS', 'PAINEL', 'ESTRIBO'],
 ['BOLSA DA PORTA', 'PAINEL', 'ALARME'],
 ['PAINEL', 'ALARME', 'ESTRIBO', 'BANCOS'],
 ['BANCOS', 'BOLSA DA PORTA', 'ESTRIBO'],
 ['PAINEL', 'BANCOS', 'ALARME', 'ESTRIBO'],
 ['BOLSA DA PORTA', 'ALARME', 'ESTRIBO'],
 ['PAINEL', 'ALARME', 'BANCOS'],
 ['BANCOS', 'BOLSA DA PORTA', 'PAINEL'],
 ['PAINEL', 'ESTRIBO', 'BANCOS'],
 ['BANCOS', 'ALARME', 'BOLSA DA PORTA', 'ESTRIBO'],
 ['PAINEL', 'ALARME', 'BANCOS', 'ESTRIBO'],
 ['BOLSA DA PORTA', 'PAINEL', 'ALARME', 'ESTRIBO'],
 ['ALARME', 'ESTRIBO', 'BANCOS'],
 ['BANCOS', 'BOLSA DA PORTA', 'ALARME'],
 ['PAINEL', 'BANCOS', 'ESTRIBO'],
 ['BOLSA DA PORTA', 'ALARME', 'PAINEL'],
 ['PAINEL', 'ALARME', 'BANCOS', 'ESTRIBO']]

In [3]:
te = TransactionEncoder()
te_ary = te.fit(transacoes).transform(transacoes)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

    ALARME  BANCOS  BOLSA DA PORTA  ESTRIBO  PAINEL
0    False    True            True     True    True
1     True    True            True    False   False
2     True   False           False     True    True
3    False    True           False     True    True
4     True   False            True    False    True
5     True    True           False     True    True
6    False    True            True     True   False
7     True    True           False     True    True
8     True   False            True     True   False
9     True    True           False    False    True
10   False    True            True    False    True
11   False    True           False     True    True
12    True    True            True     True   False
13    True    True           False     True    True
14    True   False            True     True    True
15    True    True           False     True   False
16    True    True            True    False   False
17   False    True           False     True    True
18    True   False            True    False    True
19    True    True           False     True    True

In [4]:
frequent_itemsets = apriori(df, min_support=0.5, use_colnames=True)
frequent_itemsets

   support                      itemsets
0     0.70           frozenset({ALARME})
1     0.75           frozenset({BANCOS})
2     0.50   frozenset({BOLSA DA PORTA})
3     0.70          frozenset({ESTRIBO})
4     0.70           frozenset({PAINEL})
5     0.55  frozenset({BANCOS, ESTRIBO})
6     0.50   frozenset({BANCOS, PAINEL})
7     0.50  frozenset({ESTRIBO, PAINEL})

In [6]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.5)
print(rules)

            antecedents           consequents  antecedent support  \
0   frozenset({BANCOS})  frozenset({ESTRIBO})                0.75
1  frozenset({ESTRIBO})   frozenset({BANCOS})                0.70
2   frozenset({BANCOS})   frozenset({PAINEL})                0.75
3   frozenset({PAINEL})   frozenset({BANCOS})                0.70
4  frozenset({ESTRIBO})   frozenset({PAINEL})                0.70
5   frozenset({PAINEL})  frozenset({ESTRIBO})                0.70

   consequent support  support  confidence      lift  representativity  \
0                0.70     0.55    0.733333  1.047619               1.0
1                0.75     0.55    0.785714  1.047619               1.0
2                0.70     0.50    0.666667  0.952381               1.0
3                0.75     0.50    0.714286  0.952381               1.0
4                0.70     0.50    0.714286  1.020408               1.0
5                0.70     0.50    0.714286  1.020408               1.0

   leverage  conviction  zhangs_metric   jaccard  certainty  kulczynski
0     0.025    1.125000       0.181818  0.611111   0.111111    0.759524
1     0.025    1.166667       0.151515  0.611111   0.142857    0.759524
2    -0.025    0.900000      -0.166667  0.526316  -0.111111    0.690476
3    -0.025    0.875000      -0.142857  0.526316  -0.142857    0.690476
4     0.010    1.050000       0.066667  0.555556   0.047619    0.714286
5     0.010    1.050000       0.066667  0.555556   0.047619    0.714286